// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v3.21.12
// source: protos/src/authentication.service.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "services";

export interface VerifyAuthenticationRequest {
  token: string;
}

export interface VerifyAuthenticationResponse {
}

export const SERVICES_PACKAGE_NAME = "services";

export interface AuthenticationServiceClient {
  verify(request: VerifyAuthenticationRequest, ...rest: any): Observable<VerifyAuthenticationResponse>;
}

export interface AuthenticationServiceController {
  verify(
    request: VerifyAuthenticationRequest,
    ...rest: any
  ): Promise<VerifyAuthenticationResponse> | Observable<VerifyAuthenticationResponse> | VerifyAuthenticationResponse;
}

export function AuthenticationServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["verify"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AuthenticationService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AuthenticationService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const AUTHENTICATION_SERVICE_NAME = "AuthenticationService";
